uploads = []
generated = []

[[outputs]]
id = "Clp2u6zZnL-h-i4mhePwB"
uri = "file://needs.md"
type = "text"
title = "متطلبات الـ API الناقصة (needs.md)"

[[outputs]]
id = "KTiKvdzjIMkoz1k0wf1u3"
uri = "file://needs.en.md"
type = "text"
title = "Missing API Requirements (English)"
